<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android;net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.22621.0</TargetFrameworks>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">28.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.22621.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>

	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\WebRTCme.Middleware\WebRTCme.Middleware.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.80" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.80" />
		<PackageReference Include="CommunityToolkit.Maui" Version="14.2.0" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-ios'">
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.80" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.80" />
		<PackageReference Include="CommunityToolkit.Maui" Version="14.2.0" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-maccatalyst'">
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.80" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.80" />
		<PackageReference Include="CommunityToolkit.Maui" Version="14.2.0" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows10.0.22621.0'">
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.80" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.80" />
		<PackageReference Include="CommunityToolkit.Maui" Version="14.2.0" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\..\me.png">
	    <Pack>True</Pack>
	    <PackagePath></PackagePath>
	    <Link>me.png</Link>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.JSInterop" Version="10.0.9" />
	</ItemGroup>
</Project>
