## !!!IMPORTANT!!! Using C: drive as default D: has only 14BG available space

name: WebRtcNativeWindows

on: workflow_dispatch

env:
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0
  GYP_GENERATORS: msvs-ninja,ninja
  GYP_MSVS_OVERRIDE_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise
  vs2022_install: C:\Program Files\Microsoft Visual Studio\2022\Enterprise
  GYP_MSVS_VERSION: 2022
  PYTHON_BIN_ABSDIR: C:\hostedtoolcache\windows\Python\3.9.13\x64
  
jobs:
  build:
    runs-on: windows-latest
     
    steps:
    - uses: actions/checkout@v3    
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1  
      with:
        msbuild-architecture: x64
    
    - name: Create 'depot_tools' folder
      run: |
        mkdir c:\depot_tools
        cd c:\depot_tools
        Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-infra/depot_tools.zip" -OutFile .\depot_tools.zip
        7z x -y depot_tools.zip
        del depot_tools.zip
    - name: Export 'depot_tools' path
      run: Add-Content $env:GITHUB_PATH c:\depot_tools
    - name: Execute 'gclient'
      run: gclient
    
    - name: Configure Git
      run: |
        git config --global user.name "melihercan"
        git config --global user.email "melihercan@gmail.com"
        git config --global core.autocrlf false
        git config --global core.filemode false
        git config --global branch.autosetuprebase always
        
    - name: Get the code and build
      run: |
        mkdir c:\webrtc-checkout
        cd c:\webrtc-checkout
        fetch --nohooks webrtc
        gclient sync
        cd src
        git checkout branch-heads/5481
        gclient sync
        gn gen out/Default --args='is_debug=false'
        autoninja -C out/Default
        
    - name: Copy WebRTC library
      run: |
        copy c:\webrtc-checkout\src\out\Default\obj\webrtc.lib non-code\artifacts\webrtc\windows\.
        
    - uses: actions/upload-artifact@v3
      with: 
        name: Upload WebRTC library to artifacts
        path: non-code\artifacts\webrtc\windows\webrtc.lib
        
    
